[package]
name = "konsollink-desktop"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-only"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
konsollink-platform = { path = "../../../crates/konsollink-platform" }

[features]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(target_os = "macos")'.dependencies]
konsollink-helper = { path = "../../../helper" }
